SYSTEM_PACKAGES=(
    htop
    btop
    wget
    curl
    vim
    stow
    zsh
    fzf
    openssh
)

DEV_PACKAGES=(
    nodejs
    npm
    go
    docker
    docker-compose
    neovim
    tmux
)

ARCH_DEV_PACKAGES=(
    github-cli
    python
    python-pip
    rust
)

DEB_DEV_PACKAGES=(
    gh
    python3
    python3-pip
    rustc
)

DESKTOP_PACKAGES=(
    xdg-user-dirs
    brightnessctl
    wlogout
)

ARCH_DESKTOP_PACKAGES=(
    hyprland
    hyprpaper
    hyprpicker
    hyprshot
    hyprlock
    wayle
    xdg-desktop-portal-hyprland
)

DEB_DESKTOP_DEPENDENCIES_PACKAGES=(
    meson
    wget
    build-essential
    ninja-build
    cmake-extras
    cmake
    gettext
    gettext-base
    fontconfig
    libfontconfig-dev
    libffi-dev
    libxml2-dev
    libdrm-dev
    libxkbcommon-x11-dev
    libxkbregistry-dev
    libxkbcommon-dev
    libpixman-1-dev
    libudev-dev
    libseat-dev
    seatd
    libxcb-dri3-dev
    libegl-dev
    libgles2
    libegl1-mesa-dev
    glslang-tools
    libinput-bin
    libinput-dev
    libxcb-composite0-dev
    libavutil-dev
    libavcodec-dev
    libavformat-dev
    libxcb-ewmh2
    libxcb-ewmh-dev
    libxcb-present-dev
    libxcb-icccm4-dev
    libxcb-render-util0-dev
    libxcb-res0-dev
    libxcb-xinput-dev
    libtomlplusplus3
    libre2-dev
    xdg-desktop-portal-wlr
    jq
    grim
    slurp
    wl-clipboard
    libnotify-bin
    pkg-config
    libcairo2-dev
    libpango1.0-dev
    libgbm-dev
    libdrm-dev
    libgl1-mesa-dev
    libpam0g-dev
    libwayland-dev
    wayland-protocols
    libxkbcommon-dev
)

ADDITIONAL_PACKAGES=(
    ghostty
    rofi
    dolphin
    udiskie
)

ARCH_ADDITIONAL_PACKAGES=(
    brave-bin
    visual-studio-code-bin
    ttf-jetbrains-mono-nerd
    ttf-font-awesome
)

DEB_ADDITIONAL_PACKAGES=(
    brave-browser
    fonts-jetbrains-mono
    fonts-font-awesome
)
