SYSTEM_PACKAGES=(
    htop
    btop
    wget
    curl
    vim
    stow
    zsh
    fzf
)

DEV_PACKAGES=(
    github-cli
    python
    python-pip
    nodejs
    npm
    go
    rust
    docker
    docker-compose
    neovim
    opencode
)

DESKTOP_PACKAGES=(
    xdg-user-dirs
    hyprland
    hyprpaper
    hyprpicker
    hyprshot
    hyprlock
    hyprctl
    brightnessctl
    wlogout
    swaync
    wayle 
)

ADDITIONAL_PACKAGES=(
    ghostty
    rofi
    dolphin
)

AUR_PACKAGES=(
    brave-bin
    visual-studio-code-bin
    ttf-jetbrains-mono-nerd
    ttf-font-awesome
)