set -g mouse on

# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload tmux config with prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set the base index for windows and panes to 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option  -g pane-base-index 1
set-option -g renumber-windows on

# Enable plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# Style the status bar
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-position top
set -g status-left-length 100
set -g status-style "bg=default,fg=${gray_light}"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu} 󰍛 #{mem}"
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #I #W"
set -g window-status-format " #I #W "
set -g window-style "fg=${gray_light},bg=default"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"

# Run TPM (Tmux Plugin Manager)
run '~/.tmux/plugins/tpm/tpm'
