wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/wallpaper-1.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/wallpapers/wallpaper-2.jpg
    fit_mode = cover
}
